[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "52d121a27a65d6477086a58d9ee4b6aae7e588b2"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "931c9ef9c20ae224ec009797c0fcda90426f0771b30af6ba0249a0fe61b094b7"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.aarch64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "aarch64"
git-tree-sha1 = "5cc108c222830c7f0a0f0fdafc28f44325cb21ec"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "39b316f7adba3e0d1597c854644073f58ba7117005a57b91124c0a46e38d627d"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.aarch64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "armv7l"
git-tree-sha1 = "3899511806c306885204e0d83ab8706b19620920"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "f633ce913a8bc7311b5bf37e2e74ec998ef2139326342a1b004d966d11e80fa8"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG]]
arch = "armv7l"
git-tree-sha1 = "6f1896541ead55bc56e97982c02ee22dfe133243"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "06572063e0de3b36b0586f44f036ff50187415a3e83550cef8862c5ac32a1268"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "530b0aebf39adcb1115a7687cee68067021eddef"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "93f7a25477dec24b60836da8e9ba4733c677c60ce8c8fdf2dc9087088deec589"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.i686-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "888c24663c9f80534298ee170914f27d7cfddc5c"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "1d36c30dc557bdb6f9c84b1ab1f9cad985206eb9b77f7eb6c13cf8df2517aef5"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.i686-linux-musl.tar.gz"
[[FFMPEG]]
arch = "i686"
git-tree-sha1 = "746ca0e8c708d51d0d4f1ddc18dd189cbbe1b89a"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "52725e1e582247a2ca41d2f616bb7f39bbe68668e798c9d64c4f29355f731016"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.i686-w64-mingw32.tar.gz"
[[FFMPEG]]
arch = "powerpc64le"
git-tree-sha1 = "d498abb146b8517f28442a686a1c502c952ca5fb"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "7eb326c5ded5f3a8691ba625e4f22268e9414e1382c31ca3a02623c986823d5b"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "05af98b14a5bbb8a53765e6c6920a10a76485723"
os = "macos"

    [[FFMPEG.download]]
    sha256 = "a26041280b228ee6e92cc8e1af57af38272991743c9920503bb23d4a770e4336"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.x86_64-apple-darwin14.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "d91c8a06424884898e11454ed2d681915caccd53"
libc = "glibc"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "d4d315c2371c8307e6ac6aa366dbb4419291af4ac802e84253afda387347bf9c"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.x86_64-linux-gnu.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "7191319db96830774d809591de78fbcedd41adb7"
libc = "musl"
os = "linux"

    [[FFMPEG.download]]
    sha256 = "bc4a83a0309b70292eb7dc45dc50c1d4ebf123cabb81b018897a02016cd813fa"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.x86_64-linux-musl.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "41e1dfbd0c7da6a348c2e3e54b5c0e4f5958d607"
os = "freebsd"

    [[FFMPEG.download]]
    sha256 = "dc4d3406a9217699c1f5f6c34e8e60ed921a5e5b2958df40dc83bf9f139c195f"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[FFMPEG]]
arch = "x86_64"
git-tree-sha1 = "288b40ec51122afcebef2ab9644a97c3abfb0869"
os = "windows"

    [[FFMPEG.download]]
    sha256 = "cd7def2680760e87566a8d31b56edb9774e70892e153d54e76b5e759710a1767"
    url = "https://github.com/giordano/FFMPEG_jll.jl/releases/download/FFMPEG-v4.1.0+4/FFMPEG.v4.1.0.x86_64-w64-mingw32.tar.gz"
